### ISSUE TITLE
alpha roadmap

### ISSUE THREAD

**Issue by mockuser404** [FastForwardTeam/Server#2]
- [x] Decide a programming language, framework (if any)
   - [x] Go
- [x] Decide a database
   - [x] ~MySQL~ MariaDB
- [x] Get the crowd endpoints working
- [x] Make changes to the extension code (remove hard-coded logic)
- [x] Deploy to the fastforward.team site
- [x] Test the extension with the deployment
- [x] Notify the users of the new development
- [x] Build the extension
- [x] profit

**Comment by Topkek-190** [comment]
Write it in C :)

**Comment by NotAProton** [comment]
~~Deployed the server, join the beta here: github.com/FastForwardTeam/FastForward/tree/crowd#readme~~

Beta has ended and crowdbypass has been merged into stable. All users should receive an update soon.
